default_params = dict(
    GRID_WIDTH=51,
    GRID_HEIGHT=51,
    is_bat=False,
    init_inoculum=100,
    init_dcs=50,
    init_nks=25,
    init_macros=50,
    macro_phago_recovery=0.5,
    macro_phago_limit=1_000,
    inflammasome_activation_threshold=10,  # default 50 for bats
    inflammasome_priming_threshold=1.0,  # default 5.0 for bats
    viral_carrying_capacity=500,
    susceptibility_to_infection=77,
    human_endo_activation=5,
    human_metabolic_byproduct=0.2,
    # NOT USED resistance_to_infection=75,
    viral_incubation_threshold=60,
    epi_apoptosis_threshold_lower=450,
    epi_apoptosis_threshold_range=100,
    epi_apoptosis_threshold_lower_regrow=475,
    epi_apoptosis_threshold_range_regrow=51,
    epi_regrowth_counter_threshold=432,
    epi_cell_membrane_init_lower=975,
    epi_cell_membrane_init_range=51,
    infected_epithelium_ros_damage_counter_threshold=10,
    epithelium_ros_damage_counter_threshold=2,
    epithelium_pdamps_secretion_on_death=10.0,
    dead_epithelium_pdamps_burst_secretion=10.0,
    dead_epithelium_pdamps_secretion=1.0,
    epi_max_tnf_uptake=0.1,
    epi_max_il1_uptake=0.1,
    epi_t1ifn_secretion=0.75,
    epi_t1ifn_secretion_prob=0.01,
    epi_pdamps_secretion_prob=0.01,
    infected_epi_t1ifn_secretion=1.0,
    infected_epi_il18_secretion=0.11,
    infected_epi_il6_secretion=0.10,
    activated_endo_death_threshold=0.5,
    activated_endo_adhesion_threshold=36.0,
    activated_endo_pmn_spawn_prob=0.1,
    activated_endo_pmn_spawn_dist=5.0,
    extracellular_virus_init_amount_lower=80,
    extracellular_virus_init_amount_range=40,
    human_viral_lower_bound=0.0,
    human_t1ifn_effect_scale=0.01,
    pmn_max_age=36,
    pmn_ros_secretion_on_death=10.0,
    pmn_il1_secretion_on_death=1.0,
    nk_ifng_secretion=1.0,
    macro_max_virus_uptake=10.0,
    macro_activation_threshold=5.0,
    macro_antiactivation_threshold=5.0,
    activated_macro_il8_secretion=1.0,
    activated_macro_il12_secretion=0.5,
    activated_macro_tnf_secretion=1.0,
    activated_macro_il6_secretion=0.4,
    activated_macro_il10_secretion=1.0,
    antiactivated_macro_il10_secretion=0.5,
    inflammasome_il1_secretion=1.0,
    inflammasome_macro_pre_il1_secretion=5.0,
    inflammasome_il18_secretion=1.0,
    inflammasome_macro_pre_il18_secretion=0.5,
    pyroptosis_macro_pdamps_secretion=10.0,
    dc_t1ifn_activation_threshold=1.0,
    dc_il12_secretion=0.5,
    dc_ifng_secretion=0.5,
    dc_il6_secretion=0.4,
    dc_il6_max_uptake=0.1,
    extracellular_virus_diffusion_const=0.05,
    T1IFN_diffusion_const=0.1,
    PAF_diffusion_const=0.1,
    ROS_diffusion_const=0.1,
    P_DAMPS_diffusion_const=0.1,
    IFNg_diffusion_const=0.2,
    TNF_diffusion_const=0.2,
    IL6_diffusion_const=0.2,
    IL1_diffusion_const=0.2,
    IL10_diffusion_const=0.2,
    IL12_diffusion_const=0.2,
    IL18_diffusion_const=0.2,
    IL8_diffusion_const=0.3,
    extracellular_virus_cleanup_threshold=0.05,
    cleanup_threshold=0.1,
    evap_const_1=0.99,
    evap_const_2=0.9,
)

# variables which reflect the macrostate of the model
state_vars = [
    "total_P_DAMPS",
    "total_T1IFN",
    "total_TNF",
    "total_IFNg",
    "total_IL6",
    "total_IL1",
    "total_IL8",
    "total_IL10",
    "total_IL12",
    "total_IL18",
    "total_extracellular_virus",
    "total_intracellular_virus",
    "apoptosis_eaten_counter",
    "empty_epithelium_count",
    "healthy_epithelium_count",
    "infected_epithelium_count",
    "dead_epithelium_count",
    "apoptosed_epithelium_count",
    # "system_health",
    "dc_count",
    "nk_count",
    "pmn_count",
    "macro_count",
]

state_var_indices = {s: i for i, s in enumerate(state_vars)}


# parameters of the model used only for initialization
init_only_params = [
    "init_inoculum",
    "init_dcs",
    "init_nks",
    "init_macros",
]

# true parameters of the model
variational_params = [
    # INSENSITIVE "macro_phago_recovery",
    # INSENSITIVE "macro_phago_limit",
    "inflammasome_activation_threshold",
    # INSENSITIVE "inflammasome_priming_threshold",
    # INSENSITIVE "viral_carrying_capacity",
    # INSENSITIVE "susceptibility_to_infection",
    "human_endo_activation",
    "human_metabolic_byproduct",
    # NOT USED "resistance_to_infection",
    "viral_incubation_threshold",
    "epi_apoptosis_threshold_lower",
    # INSENSITIVE "epi_apoptosis_threshold_range",
    # INSENSITIVE "epi_apoptosis_threshold_lower_regrow",
    # INSENSITIVE "epi_apoptosis_threshold_range_regrow",
    # INSENSITIVE "epi_regrowth_counter_threshold",
    # INSENSITIVE "epi_cell_membrane_init_lower",
    # INSENSITIVE "epi_cell_membrane_init_range",
    # INSENSITIVE "infected_epithelium_ros_damage_counter_threshold",
    "epithelium_ros_damage_counter_threshold",
    "epithelium_pdamps_secretion_on_death",
    # INSENSITIVE "dead_epithelium_pdamps_burst_secretion",
    # INSENSITIVE "dead_epithelium_pdamps_secretion",
    # INSENSITIVE "epi_max_tnf_uptake",
    # INSENSITIVE "epi_max_il1_uptake",
    # INSENSITIVE "epi_t1ifn_secretion",
    # INSENSITIVE "epi_t1ifn_secretion_prob",
    # INSENSITIVE "epi_pdamps_secretion_prob",
    "infected_epi_t1ifn_secretion",
    # INSENSITIVE "infected_epi_il18_secretion",
    # INSENSITIVE "infected_epi_il6_secretion",
    "activated_endo_death_threshold",
    # INSENSITIVE "activated_endo_adhesion_threshold",
    "activated_endo_pmn_spawn_prob",
    "activated_endo_pmn_spawn_dist",
    "extracellular_virus_init_amount_lower",
    # INSENSITIVE "extracellular_virus_init_amount_range",
    # INSENSITIVE "human_t1ifn_effect_scale",
    # INSENSITIVE "pmn_max_age",
    "pmn_ros_secretion_on_death",
    "pmn_il1_secretion_on_death",
    # INSENSITIVE "nk_ifng_secretion",
    # INSENSITIVE "macro_max_virus_uptake",
    "macro_activation_threshold",
    # INSENSITIVE "macro_antiactivation_threshold",
    # INSENSITIVE "activated_macro_il8_secretion",
    # INSENSITIVE "activated_macro_il12_secretion",
    "activated_macro_tnf_secretion",
    # INSENSITIVE "activated_macro_il6_secretion",
    # INSENSITIVE "activated_macro_il10_secretion",
    # INSENSITIVE "antiactivated_macro_il10_secretion",
    "inflammasome_il1_secretion",
    "inflammasome_macro_pre_il1_secretion",
    # INSENSITIVE "inflammasome_il18_secretion",
    # INSENSITIVE "inflammasome_macro_pre_il18_secretion",
    # INSENSITIVE "pyroptosis_macro_pdamps_secretion",
    # INSENSITIVE "dc_t1ifn_activation_threshold",
    # INSENSITIVE "dc_il12_secretion",
    # INSENSITIVE "dc_ifng_secretion",
    # INSENSITIVE "dc_il6_secretion",
    # INSENSITIVE "dc_il6_max_uptake",
    # # ACK's Executive Judgement: These are physics-like parameters and won't vary between individuals.
    # # They also include model-intrinsic things like a cleanup thresholds which don't precisely
    # # correspond to read world objects.
    # "human_viral_lower_bound", # 0.0
    # "extracellular_virus_diffusion_const",
    # "T1IFN_diffusion_const",
    # "PAF_diffusion_const",
    # "ROS_diffusion_const",
    # "P_DAMPS_diffusion_const",
    # "IFNg_diffusion_const",
    # "TNF_diffusion_const",
    # "IL6_diffusion_const",
    # "IL1_diffusion_const",
    # "IL10_diffusion_const",
    # "IL12_diffusion_const",
    # "IL18_diffusion_const",
    # "IL8_diffusion_const",
    # "extracellular_virus_cleanup_threshold",
    # "cleanup_threshold",
    # "evap_const_1",
    # "evap_const_2",
]

variational_params_indices = {s: i + len(state_vars) for i, s in enumerate(state_vars)}


UNIFIED_STATE_SPACE_DIMENSION = len(state_vars) + len(variational_params)

assert all(param in default_params for param in variational_params)
